apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/version: {{ .Values.mediawiki.image.tag }}
  {{- with .Values.mediawiki.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mediawiki.service.type }}
  ports:
    - port: {{ .Values.mediawiki.service.port }}
      targetPort: {{ .Values.mediawiki.context.ports.server }}
      protocol: TCP
      name: server
  selector:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/instance: {{ .Release.Name }}