name: create-docker

on:
  push:
    branches:
      - 'main'
    paths:
      -  CI/**
      - '!CI/helm/**'
jobs:
  create-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013 #v1.1.0
    - name: Clean up runner
      run: |
        rm -f ~/.ssh/*
        rm -f ~/.gitconfig
    - name: Checkout Repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: push to docker hub
      run: |
         cd CI
         docker build -f Dockerfile -t santhos663/mediawiki:latest .
         docker push santhos663/mediawiki:latest