name: create-helm

on:
  push:
    branches:
      - 'main'
    paths:
      - CI/helm/**
jobs:
  build-and-push-helm:
    name: build
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013 #v1.1.0
    - name: Clean up runner
      run: |
        rm -f ~/.ssh/*
        rm -f ~/.gitconfig
    - name: Checkout Repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: package 
      run: |
        cd CI/helm/media_wiki
        helm package .
    - name: push
      run: |
        cd CI/helm/media_wiki
        helmpackage=$(ls | grep media_wiki.)
        az acr helm push $helmpackage --name santhosregistry.azurecr.io/helm
